# Microsoft Entra External ID の呼び出し設定（テスト環境用テナント）
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://{tenant-id}.ciamlogin.com/{tenant-id}/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=client-id
