# Microsoft Entra External ID の呼び出し設定（開発環境用テナント）
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://{tenant-id}.ciamlogin.com/{tenant-id}/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=client-id

# ヘルスチェックの API のログを検出するため logging level を変更する
logging.level.web=DEBUG

# ログの詳細化
logging.level.org.springframework.security=DEBUG

# CORS 設定
cors.allowed.origins=http://localhost,http://localhost:5173