---
# cspell:ignore cooldown
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/workflows/*"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "github-actions"
    labels:
      - "CI/CD"
      - "dependencies"
    target-branch: "main"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    commit-message:
      prefix: "python"
    labels:
      - "pip"
      - "dependencies"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    commit-message:
      prefix: "npm-root"
    labels:
      - "npm"
      - "dependencies"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "/samples/web-csr/dressca-frontend"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 60
    commit-message:
      prefix: "npm-dressca-frontend"
    labels:
      - "target: Dressca"
      - "npm"
      - "dependencies"
    target-branch: "main"

  - package-ecosystem: "gradle"
    directory: "/samples/web-csr/dressca-backend"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 20
    commit-message:
      prefix: "gradle-dressca-backend"
    labels:
      - "target: Dressca"
      - "gradle"
      - "dependencies"
    target-branch: "main"

  # Azure AD B2C
  - package-ecosystem: "npm"
    directory: "/samples/azure-ad-b2c-sample/auth-frontend"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 40
    commit-message:
      prefix: "npm-auth-frontend"
    labels:
      - "target: Azure AD B2C Auth"
      - "npm"
      - "dependencies"
    target-branch: "main"

  - package-ecosystem: "gradle"
    directory: "/samples/azure-ad-b2c-sample/auth-backend"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 20
    commit-message:
      prefix: "gradle-auth-backend"
    labels:
      - "target: Azure AD B2C Auth"
      - "gradle"
      - "dependencies"
    target-branch: "main"

  # External ID for SPA
  - package-ecosystem: "npm"
    directory: "/samples/external-id-sample-for-spa/auth-frontend"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 40
    commit-message:
      prefix: "npm-external-id-for-spa"
    labels:
      - "target: EntraID External ID"
      - "npm"
      - "dependencies"
    target-branch: "main"

  - package-ecosystem: "gradle"
    directory: "/samples/external-id-sample-for-spa/auth-backend"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 20
    commit-message:
      prefix: "gradle-external-id-for-spa"
    labels:
      - "target: EntraID External ID"
      - "gradle"
      - "dependencies"
    target-branch: "main"

  # Dressca CMS
  - package-ecosystem: "gradle"
    directory: "/samples/dressca-cms"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 20
    commit-message:
      prefix: "gradle-dressca-cms"
    labels:
      - "target: Dressca-CMS"
      - "gradle"
      - "dependencies"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "/samples/dressca-cms/web/src/main/resources/static/bootstrap"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 20
    commit-message:
      prefix: "npm-dressca-cms"
    labels:
      - "target: Dressca-CMS"
      - "npm"
      - "dependencies"
    groups:
      bootstrap-packages:
        patterns:
          - "bootstrap*"
        update-types:
          - "minor"
          - "patch"
    target-branch: "main"
