changelog:
  categories:
    - title: ':newspaper: Features'
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - 内部の改善
    - title: ':label: :green_circle: Gradle package dependencies'
      labels:
        - gradle
    - title: ':label: :white_circle: npm package dependencies'
      labels:
        - npm
    - title: ':label: Other dependencies'
      labels:
        - dependencies
      exclude:
        labels:
          - gradle
          - npm
    - title: ':lollipop: improvements in development'
      labels:
        - 内部の改善
