changelog:
  categories:
    - title: ':newspaper: Features'
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - 内部の改善
          - 不具合
    - title: ':wrench: Bug fixes'
      labels:
        - 不具合
    - title: ':label: :green_circle: Gradle package dependencies'
      labels:
        - gradle
    - title: ':label: :white_circle: npm package dependencies'
      labels:
        - npm
    - title: ':label: Other dependencies'
      labels:
        - dependencies
      exclude:
        labels:
          - gradle
          - npm
    - title: ':lollipop: improvements in development'
      labels:
        - 内部の改善
