/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/authentication/login': RouteRecordInfo<
      '/authentication/login',
      '/authentication/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalog/items/': RouteRecordInfo<
      '/catalog/items/',
      '/catalog/items',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalog/items/add': RouteRecordInfo<
      '/catalog/items/add',
      '/catalog/items/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalog/items/edit/[itemId]': RouteRecordInfo<
      '/catalog/items/edit/[itemId]',
      '/catalog/items/edit/:itemId',
      { itemId: ParamValue<true> },
      { itemId: ParamValue<false> },
      | never
    >,
    '/error': RouteRecordInfo<
      '/error',
      '/error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/authentication/login.vue': {
      routes:
        | '/authentication/login'
      views:
        | never
    }
    'src/pages/catalog/items/index.vue': {
      routes:
        | '/catalog/items/'
      views:
        | never
    }
    'src/pages/catalog/items/add.vue': {
      routes:
        | '/catalog/items/add'
      views:
        | never
    }
    'src/pages/catalog/items/edit/[itemId].vue': {
      routes:
        | '/catalog/items/edit/[itemId]'
      views:
        | never
    }
    'src/pages/error.vue': {
      routes:
        | '/error'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
