customRules:
  - custom-lint-rules/requires-title-and-description.js

gitignore: true

# Github の Issues や Pull requests に使用されるテンプレート用の md はテスト対象から除外する
# Github の Issues や Pull requests に設定の Tag が含まれることを防ぐため yaml 上で除外設定を実行する 
globs:
  - "!**/.github/**/*.md"