# AzureADB2Cの呼び出し設定（開発環境用テナント）
spring.cloud.azure.active-directory.b2c.base-uri=https://domain-name.b2clogin.com/domain-name.onmicrosoft.com/
spring.cloud.azure.active-directory.b2c.credential.client-id=client-id
spring.cloud.azure.active-directory.b2c.profile.tenant-id=tenant-id
spring.cloud.azure.active-directory.b2c.user-flows.sign-up-or-sign-in=B2C_1_user-flows
# ヘルスチェックの API のログを検出するため logging level を変更する
logging.level.web=DEBUG

# ログの詳細化
logging.level.org.springframework.security=DEBUG

# CORS 設定
cors.allowed.origins=http://localhost,http://localhost:5173