# springdoc-openapi
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true
# Open API 仕様書を自動生成する際keyをアルファベット順でソートする
springdoc.writer-with-order-by-keys=true

# messages.properties
spring.messages.basename=systemcommon.messages
spring.messages.encoding=UTF-8

# 構造化ログのフォーマットの指定
logging.structured.format.console=ecs

# AzureADB2Cの呼び出し設定（有効化フラグは全環境共通）
spring.cloud.azure.active-directory.b2c.enabled=true