# AzureADB2Cの呼び出し設定（本番環境用テナント）
spring.cloud.azure.active-directory.b2c.base-uri=https://domain-name.b2clogin.com/domain-name.onmicrosoft.com/
spring.cloud.azure.active-directory.b2c.credential.client-id=client-id
spring.cloud.azure.active-directory.b2c.profile.tenant-id=tenant-id
spring.cloud.azure.active-directory.b2c.user-flows.sign-up-or-sign-in=B2C_1_user-flows

# CORS 設定
cors.allowed.origins=https://本番環境のフロントエンド配布サーバーのドメイン