/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AccountDto } from './account-dto';
import { BasketItemDto } from './basket-item-dto';

/**
 * 
 * @export
 * @interface BasketDto
 */
export interface BasketDto {
    /**
     * 
     * @type {string}
     * @memberof BasketDto
     */
    'buyerId'?: string;
    /**
     * 
     * @type {AccountDto}
     * @memberof BasketDto
     */
    'account'?: AccountDto;
    /**
     * 
     * @type {Array<BasketItemDto>}
     * @memberof BasketDto
     */
    'basketItems'?: Array<BasketItemDto>;
}

