/* tslint:disable */
/* eslint-disable */
/**
 * Dressca
 * ECサイトDressca
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CatalogItemSummaryResponse
 */
export interface CatalogItemSummaryResponse {
    /**
     * 
     * @type {number}
     * @memberof CatalogItemSummaryResponse
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemSummaryResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemSummaryResponse
     */
    'productCode'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogItemSummaryResponse
     */
    'assetCodes'?: Array<string>;
}

