/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CatalogItem } from './catalog-item';

/**
 * 
 * @export
 * @interface CatalogItemAsset
 */
export interface CatalogItemAsset {
    /**
     * 
     * @type {CatalogItem}
     * @memberof CatalogItemAsset
     */
    'catalogItem'?: CatalogItem;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemAsset
     */
    'assetCode'?: string;
}

