/* tslint:disable */
/* eslint-disable */
/**
 * Dressca
 * ECサイトDressca
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CatalogItem } from './catalog-item';

/**
 * 
 * @export
 * @interface CatalogBrand
 */
export interface CatalogBrand {
    /**
     * 
     * @type {number}
     * @memberof CatalogBrand
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CatalogBrand
     */
    'name'?: string;
    /**
     * 
     * @type {Array<CatalogItem>}
     * @memberof CatalogBrand
     */
    'items'?: Array<CatalogItem>;
}

