/* tslint:disable */
/* eslint-disable */
/**
 * Dressca
 * ECサイトDressca
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CatalogBrand } from './catalog-brand';
import { CatalogCategory } from './catalog-category';
import { CatalogItemAsset } from './catalog-item-asset';

/**
 * 
 * @export
 * @interface CatalogItem
 */
export interface CatalogItem {
    /**
     * 
     * @type {number}
     * @memberof CatalogItem
     */
    'id'?: number;
    /**
     * 
     * @type {Array<CatalogItemAsset>}
     * @memberof CatalogItem
     */
    'assets'?: Array<CatalogItemAsset>;
    /**
     * 
     * @type {CatalogCategory}
     * @memberof CatalogItem
     */
    'catalogCategory'?: CatalogCategory;
    /**
     * 
     * @type {CatalogBrand}
     * @memberof CatalogItem
     */
    'catalogBrand'?: CatalogBrand;
    /**
     * 
     * @type {string}
     * @memberof CatalogItem
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItem
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof CatalogItem
     */
    'price'?: number;
    /**
     * 
     * @type {string}
     * @memberof CatalogItem
     */
    'productCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof CatalogItem
     */
    'catalogCategoryId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CatalogItem
     */
    'catalogBrandId'?: number;
}

