/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CatalogItemDto
 */
export interface CatalogItemDto {
    /**
     * 
     * @type {number}
     * @memberof CatalogItemDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'productCode'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogItemDto
     */
    'assetCodes'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDto
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof CatalogItemDto
     */
    'price'?: number;
    /**
     * 
     * @type {number}
     * @memberof CatalogItemDto
     */
    'catalogCategoryId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CatalogItemDto
     */
    'catalogBrandId'?: number;
}

