/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CatalogItemSummaryDto } from './catalog-item-summary-dto';

/**
 * 
 * @export
 * @interface OrderItemDto
 */
export interface OrderItemDto {
    /**
     * 
     * @type {number}
     * @memberof OrderItemDto
     */
    'Id'?: number;
    /**
     * 
     * @type {CatalogItemSummaryDto}
     * @memberof OrderItemDto
     */
    'itemOrdered'?: CatalogItemSummaryDto;
    /**
     * 
     * @type {number}
     * @memberof OrderItemDto
     */
    'quantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItemDto
     */
    'subTotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItemDto
     */
    'id'?: number;
}

