/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AccountDto } from './account-dto';
import { OrderItemDto } from './order-item-dto';

/**
 * 
 * @export
 * @interface OrderDto
 */
export interface OrderDto {
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    'buyerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    'orderDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    'fullName'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    'postalCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    'todofuken'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    'shikuchoson'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    'azanaAndOthers'?: string;
    /**
     * 
     * @type {AccountDto}
     * @memberof OrderDto
     */
    'account'?: AccountDto;
    /**
     * 
     * @type {Array<OrderItemDto>}
     * @memberof OrderDto
     */
    'orderItems'?: Array<OrderItemDto>;
    /**
     * 
     * @type {number}
     * @memberof OrderDto
     */
    'id'?: number;
}

