/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CatalogItemDto } from './catalog-item-dto';

/**
 * 
 * @export
 * @interface PagedCatalogItemDto
 */
export interface PagedCatalogItemDto {
    /**
     * 
     * @type {Array<CatalogItemDto>}
     * @memberof PagedCatalogItemDto
     */
    'items'?: Array<CatalogItemDto>;
    /**
     * 
     * @type {number}
     * @memberof PagedCatalogItemDto
     */
    'totalCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedCatalogItemDto
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedCatalogItemDto
     */
    'pageSize'?: number;
}

