/* tslint:disable */
/* eslint-disable */
/**
 * Dressca
 * ECサイトDressca
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PutBasketItemRequest
 */
export interface PutBasketItemRequest {
    /**
     * 
     * @type {number}
     * @memberof PutBasketItemRequest
     */
    'catalogItemId'?: number;
    /**
     * 
     * @type {number}
     * @memberof PutBasketItemRequest
     */
    'quantity'?: number;
}

