/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BasketDto } from '../models';
/**
 * BasketItemControllerApi - axios parameter creator
 * @export
 */
export const BasketItemControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} catalogItemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBasketItemAsync: async (catalogItemId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'catalogItemId' is not null or undefined
            assertParamExists('deleteBasketItemAsync', 'catalogItemId', catalogItemId)
            const localVarPath = `/api/basket-items/{catalogItemId}`
                .replace(`{${"catalogItemId"}}`, encodeURIComponent(String(catalogItemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBasketItems: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/basket-items`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BasketItemControllerApi - functional programming interface
 * @export
 */
export const BasketItemControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BasketItemControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} catalogItemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteBasketItemAsync(catalogItemId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteBasketItemAsync(catalogItemId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBasketItems(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BasketDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBasketItems(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * BasketItemControllerApi - factory interface
 * @export
 */
export const BasketItemControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BasketItemControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {number} catalogItemId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBasketItemAsync(catalogItemId: number, options?: any): AxiosPromise<object> {
            return localVarFp.deleteBasketItemAsync(catalogItemId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBasketItems(options?: any): AxiosPromise<BasketDto> {
            return localVarFp.getBasketItems(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BasketItemControllerApi - object-oriented interface
 * @export
 * @class BasketItemControllerApi
 * @extends {BaseAPI}
 */
export class BasketItemControllerApi extends BaseAPI {
    /**
     * 
     * @param {number} catalogItemId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BasketItemControllerApi
     */
    public deleteBasketItemAsync(catalogItemId: number, options?: AxiosRequestConfig) {
        return BasketItemControllerApiFp(this.configuration).deleteBasketItemAsync(catalogItemId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BasketItemControllerApi
     */
    public getBasketItems(options?: AxiosRequestConfig) {
        return BasketItemControllerApiFp(this.configuration).getBasketItems(options).then((request) => request(this.axios, this.basePath));
    }
}
