---

name: dressca-root-frontend CI

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
    paths:
      - 'samples/web-csr/dressca-frontend/*.*'
      - '.github/workflows/samples-dressca-root-frontend-ci.yml'
  workflow_dispatch:

defaults:
  run:
    working-directory: samples/web-csr/dressca-frontend/

jobs:
  check:
    name: Dressca モノレポのルートプロジェクトのチェック
    runs-on: ubuntu-latest
    env:
      NO_COLOR: "1"  # 文字化け防止のためカラーコードを出力しない
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - name: Use Node.js LTS
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444  # v5.0.0
        with:
          node-version: lts/*
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          cache: npm
      - name: node パッケージのインストール
        run: npm ci
      - id: run-format
        name: format の実行
        run: npm run format:ci:root >> /var/tmp/format-result.txt 2>&1

      - name: format の結果出力
        if: ${{ success() || (failure() && steps.run-format.conclusion == 'failure') }}
        uses: ./.github/workflows/file-to-summary
        with:
          body: /var/tmp/format-result.txt
          header: 'format の結果 :pen:'